# Generated by Django 6.0.1 on 2026-02-01 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('inappropriate', 'Uyğun olmayan məzmun'), ('spam', 'Spam'), ('offensive', 'Təhqiredici/Saldırğan'), ('misinformation', 'Yanlış məlumat'), ('copyright', 'Müəlliflik hüququ ihlali'), ('other', 'Digər səbəb')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('post', 'reporter_email')},
            },
        ),
    ]
